package org.example.ai_content_creator_hub.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;
import org.example.ai_content_creator_hub.entity.auth.User;

import java.time.LocalDateTime;

/**
 * Represents generated content within the system.
 * This entity is used to store content created during user interactions,
 * generated by various sources, and categorized by type, role, and source.
 *
 * The content may be associated with a specific user and optionally linked to a conversation.
 *
 * Annotations:
 * - @Entity: Indicates that this class is a JPA entity.
 * - @Getter: Automatically generates getter methods for all fields.
 * - @Setter: Automatically generates setter methods for all fields.
 * - @ToString: Automatically generates a toString method for debugging purposes.
 */
@Getter
@Setter
@ToString
@Entity
public class GeneratedContent {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private ContentType contentType; // Text, Summary, etc.

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private ContentRole contentRole; // User, Assistant, System

    @Column(nullable = false)
    @Enumerated(EnumType.STRING)
    private ContentSource contentSource; // Source of the content: OpenAI, GoogleNLP, etc.

    @Lob
    @Column(nullable = false)
    private String content;

    private LocalDateTime generatedAt;

    @ManyToOne
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    @ManyToOne
    @JoinColumn(name = "conversation_id") // Link to the conversation
    private Conversation conversation;
}
